# Generated by Django 5.2 on 2025-04-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
