# Generated by Django 5.2 on 2025-04-19 03:18

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_post_created_date_post_created_post_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/images"),
        ),
    ]
