# Generated by Django 5.2 on 2025-04-28 03:35

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="default-post-slug", max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
