# Generated by Django 5.2 on 2025-05-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_like_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="name",
        ),
    ]
