# Generated by Django 5.2 on 2025-05-10 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_remove_comment_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="email",
        ),
    ]
