# Generated by Django 5.2 on 2025-05-11 13:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_remove_post_comments_remove_post_likes_like_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="value",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(1, "Like"), (-1, "Dislike")], max_length=10, null=True
            ),
        ),
    ]
