# Generated by Django 5.2 on 2025-05-11 15:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_alter_like_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="value",
            field=models.SmallIntegerField(blank=True, choices=[(1, "Like"), (-1, "Dislike")], null=True),
        ),
    ]
