name: Automated Tests

on:
  [push, pull_request]

jobs:
  test:
    name: Continuos Integration
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.13]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test --keepdb --failfast
    env:
      POSTGRES_DB: blog
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
      POSTGRES_HOST: db
      ENVIRONMENT: development
